import os, random
os.environ['SECRET_KEY'] = 'seeding'
from slugify import slugify
from database import SessionLocal
from models import Product, Category

PLATFORMS = ['amazon', 'daraz', 'alibaba', 'aliexpress']
CURRENCIES = ['USD', 'PKR', 'EUR', 'GBP']

PRODUCTS = {
    'beauty': ([
        'Organic Face Serum Vitamin C', 'Hydrating Night Cream 50ml', 'Matte Lipstick Long Lasting',
        'Volumizing Mascara Waterproof', 'Charcoal Face Mask Deep Cleansing', 'Argan Oil Hair Treatment',
        'Eye Shadow Palette 12 Colors', 'Setting Spray For Makeup', 'Nail Polish Gel Kit 6 Colors',
        'Facial Cleansing Brush Electric', 'Under Eye Patches Gold 24K', 'Lip Gloss Plumping Shine',
        'BB Cream SPF 30', 'Highlighting Powder Palette', 'Eyelash Curler Professional',
        'Cuticle Oil Nail Care', 'Brow Pencil Waterproof', 'Concealer Full Coverage',
        'Blush Brush Set Professional', 'Toner Face Mist Rose Water', 'Sunscreen SPF 50 Face',
        'Makeup Sponge Set 5 Pack', 'Lip Scrub Sugar Natural', 'Hair Mask Keratin Treatment',
        'Face Powder Translucent', 'Eyeliner Pen Waterproof Black', 'Primer Face Pore Minimizing',
        'Contour Stick Cream', 'False Eyelashes Natural 5 Pair', 'Setting Powder Loose',
        'Lip Stain Long Wear', 'Face Wash Gel Purifying', 'Tinted Moisturizer Daily',
        'Eye Cream Anti Aging', 'Heat Protectant Spray Hair', 'Makeup Brush Cleaner',
        'Brow Gel Clear', 'Highlighter Stick Cream', 'Lip Liner Pencil Set',
        'Face Mist Dewy Glow', 'Hair Oil Argan Natural', 'Powder Puff Set 3 Pack',
        'Eye Primer Long Lasting', 'Lip Mask Overnight', 'Face Roller Jade',
        'Hair Clips Sectioning 4 Pack', 'Setting Powder Banana', 'Lip Oil Glossy Shine',
        'Face Steamer Home Spa', 'Eyebrow Stamp Kit 2 Shapes',
    ], (5, 80)),
    'electronics': ([
        'Wireless Bluetooth Earbuds 5.3', 'Portable Power Bank 20000mAh', 'Smart Watch Fitness Tracker',
        'USB C Hub 7 in 1', 'Noise Cancelling Headphones', 'LED Desk Lamp Touch Control',
        'Bluetooth Speaker Waterproof', 'Wireless Charger Fast 15W', 'HDMI Cable 4K 6ft',
        'Smart Plug WiFi Compatible', 'External SSD 1TB Portable', 'Webcam 1080p USB',
        'Mechanical Keyboard RGB', 'Wireless Mouse Ergonomic', 'Phone Stand Adjustable',
        'Dash Cam 1080p Car', 'Electric Toothbrush Sonic', 'Air Purifier HEPA Filter',
        'Digital Alarm Clock Large', 'VR Headset 3D Glasses', 'Smart Light Bulb RGB',
        'Laptop Stand Adjustable', 'Cable Organizer Box', 'Car Phone Mount Holder',
        'Surge Protector Power Strip', 'Memory Card 128GB MicroSD', 'Tablet Stand Foldable',
        'Electric Kettle Stainless', 'Gaming Mouse Pad RGB', 'USB Microphone Podcast',
        'Ring Light 10 inch', 'Screen Protector Tempered Glass', 'Laptop Cooling Pad',
        'Wireless Keyboard Slim', 'Action Camera Waterproof', 'Portable Projector Mini',
        'Smart Scale Body Fat', 'Electric Shaver Men', 'Hair Dryer Ionic 1800W',
        'Robot Vacuum Cleaner', 'Digital Thermometer Infrared', 'Mouse Pad Wrist Support',
        'Monitor Stand Riser', 'USB Fan Mini Desktop', 'Cable Ties Reusable 10 Pack',
        'Phone Ring Holder Grip', 'Wireless Earbuds Case', 'HDMI Splitter 4K',
        'Desk Organizer Mesh', 'iPhone Screen Cleaning Kit',
    ], (10, 200)),
    'fashion': ([
        'Men Casual Shirt Cotton', 'Women Summer Dress Floral', 'Slim Fit Jeans Stretch',
        'Leather Jacket Men Classic', 'Cashmere Sweater Women', 'Denim Jacket Distressed',
        'Polo Shirt Cotton Pique', 'Maxi Dress Boho Print', 'Chinos Pants Slim Fit',
        'Blazer Men Navy Blue', 'Silk Blouse Women Elegant', 'Cargo Pants Multi Pocket',
        'Trench Coat Women Belted', 'Hoodie Men Pullover', 'Leather Belt Premium',
        'Cardigan Women Knitted', 'Tuxedo Suit Men 2 Piece', 'Linen Shirt Breathable',
        'Puffer Jacket Quilted', 'Wool Scarf Cashmere Blend', 'Vest Men Formal',
        'Tunic Top Women Printed', 'Overalls Denim Dungaree', 'Raincoat Waterproof Hooded',
        'Sherpa Jacket Fleece', 'Kurta Men Ethnic Cotton', 'Shrug Women Open Front',
        'Shorts Men Chino', 'Jumpsuit Women Romper', 'Belt Bag Fanny Pack',
        'Tracksuit Men 2 Piece', 'Leggings Women High Waist', 'Button Down Shirt Oxford',
        'Bomber Jacket Satin', 'Poncho Cape Women', 'Waistcoat Men Formal',
        'Skirt Pleated Mini', 'Parka Jacket Insulated', 'Hawaiian Shirt Men Print',
        'Bodycon Dress Women', 'Coat Wool Long', 'Sweatpants Men Jogger',
        'Tank Top Men Cotton', 'Blazer Women Office', 'Henley Shirt Long Sleeve',
        'Top Crop Women', 'Varsity Jacket Wool Blend', 'Dungaree Shorts Denim',
        'Knit Sweater Crew Neck', 'Corduroy Pants Men',
    ], (15, 150)),
    'home-kitchen': ([
        'Nonstick Frying Pan 12 inch', 'Glass Food Storage Set 10pc', 'Coffee Maker Drip 12 Cup',
        'Knife Block Set Kitchen', 'Cutting Board Bamboo Large', 'Mixing Bowl Set Stainless',
        'Kitchen Towel Set absorbent', 'Measuring Spoon Set Magnetic', 'Peeler Vegetable Swivel',
        'Blender Smoothie 1000W', 'Toaster 2 Slice Wide', 'Can Opener Electric Automatic',
        'Spatula Turner Silicone', 'Water Bottle Glass 1L', 'Ice Cube Tray Silicone',
        'Food Scale Digital Kitchen', 'Garlic Press Stainless Steel', 'Rolling Pin Marble',
        'Salt And Pepper Grinder Set', 'Teapot Glass Infuser', 'Microwave Oven 20L',
        'Rice Cooker 5 Cup', 'Pot Set Stainless 8pc', 'Juicer Citrus Manual',
        'Wok Pan Carbon Steel 14in', 'Muffin Pan Nonstick 12 Cup', 'Colander Strainer Mesh',
        'Kitchen Shears Heavy Duty', 'Pizza Cutter Rocker', 'Measuring Cup Glass 4 Cup',
        'Lunch Box Bento Adult', 'Thermos Flask Vacuum', 'Cake Pan Springform',
        'Vegetable Chopper Pro', 'Dish Drying Mat Large', 'Apron Kitchen Waterproof',
        'Oven Mitt Set Heat Resistant', 'Tongs Kitchen Silicone', 'Cheese Grater Stainless',
        'Mortar And Pestle Granite', 'Milk Frother Electric', 'Pan Lid Organizer Rack',
        'Food Container BPA Free 5pc', 'Sink Organizer Caddy', 'Spice Rack Wall Mounted',
        'Trash Can Kitchen 13 Gal', 'Dish Rack Over Sink', 'Bread Box Bamboo',
        'Soap Dispenser Automatic', 'Utensil Holder Countertop',
    ], (5, 150)),
    'sports': ([
        'Yoga Mat Premium Non Slip', 'Dumbbell Set Adjustable 20kg', 'Resistance Bands Set 5 Pack',
        'Jump Rope Speed Steel', 'Foam Roller Muscle Recovery', 'Kettlebell Cast Iron 12kg',
        'Gym Gloves Men Women', 'Ab Wheel Roller Pro', 'Push Up Stand Parallettes',
        'Weight Bench Foldable', 'Pull Up Bar Doorway', 'Skipping Rope Digital Counter',
        'Ankle Weights Adjustable 5kg', 'Exercise Ball Stability 65cm', 'Water Bottle Shaker 700ml',
        'Gym Bag Duffel Large', 'Sweatband Headband Athletic', 'Boxing Gloves 12oz',
        'Tennis Racket Pro Strung', 'Basketball Outdoor Rubber', 'Soccer Ball Size 5',
        'Badminton Set 4 Racket', 'Golf Club Set Men', 'Yoga Block Cork Set 2',
        'Resistance Loop Bands', 'Running Belt Phone Holder', 'Pilates Ring Magic Circle',
        'Medicine Ball 6kg', 'Hand Grip Strengthener Adjustable', 'Swimming Goggles Anti Fog',
        'Cycling Gloves Padded', 'Pool Noodle Floating', 'Hiking Backpack 40L',
        'Shin Guards Soccer', 'Fitness Tracker Wristband', 'Wrist Wraps Gym Support',
        'Knee Sleeve Compression', 'Cooling Towel Sports', 'Protein Shaker Bottle 600ml',
        'Speed Ladder Agility', 'Tennis Balls Can 3 Pack', 'Yoga Strap Cotton 8ft',
        'Weight Lifting Belt Leather', 'Jump Box Plyometric', 'Sweat Waist Trimmer Neoprene',
        'Balance Board Trainer', 'Step Platform Aerobic', 'Battle Rope 50ft',
        'Punching Bag Stand', 'Recovery Sandals Post Workout',
    ], (8, 120)),
    'health-fitness': ([
        'Digital Body Scale BMI', 'Blood Pressure Monitor Automatic', 'Fitness Tracker Smart Band',
        'Essential Oil Diffuser Ultrasonic', 'Posture Corrector Adjustable', 'Neck Massager Shiatsu',
        'Foot Massager Electric', 'Back Stretcher Lumbar Support', 'Massage Gun Deep Tissue',
        'Acupressure Mat Set Pillow', 'Heat Patch Therapeutic 10pk', 'Hand Massager Arthritis',
        'Infrared Sauna Blanket', 'Compression Socks Circulation', 'TENS Unit Muscle Stimulator',
        'Sleep Mask Silk Blackout', 'Aromatherapy Diffuser 300ml', 'Humidifier Cool Mist 2L',
        'Heated Blanket Throw Size', 'Therapy Lamp Light 10000 Lux', 'Knee Brace Support Adjustable',
        'Ankle Brace Stabilizer', 'Wrist Support Carpal Tunnel', 'Neck Pillow Memory Foam',
        'Lumbar Cushion Car Seat', 'Heating Pad Electric Moist', 'Essential Oil Lavender 10ml',
        'Fitness Mat Extra Thick', 'Water Bottle Motivational 2L', 'Sleep Aid Natural Supplement',
        'Vitamin Organizer Pill Box', 'Glucometer Blood Sugar Monitor', 'Weighing Scale Kitchen Food',
        'Yoga Towel Non Slip', 'Gym Sack Backpack Drawstring', 'Foam Roller High Density',
        'Muscle Roller Stick Massage', 'Fitness Journal Planner', 'Shaker Bottle Protein 500ml',
        'Headband Sweatband Terry', 'Waist Trainer Corset', 'Push Up Board System',
        'Pull Up Assist Bands', 'Pilates Ball Mini 9 inch', 'Agility Ladder Speed Training',
        'Jump Rope Bearing Speed', 'Weighted Vest 10kg', 'Dipping Bars Parallel',
        'Resistance Tube Set Door Anchor', 'Vibration Platform Machine',
    ], (5, 100)),
    'toys-games': ([
        'Building Blocks 500 Piece', 'Remote Control Car Fast', 'Puzzle 1000 Piece Landscape',
        'Board Game Strategy Family', 'Action Figure Superhero 12in', 'Rubik Cube Speed 3x3',
        'Card Game UNO Classic', 'Water Gun Super Soaker', 'Drone Quadcopter With Camera',
        'Play Dough Set 24 Colors', 'Stuffed Bear Plush 18in', 'Toy Train Set Electric',
        'Lego Classic Building Bricks', 'Nerf Gun Blaster Elite', 'Science Kit Chemistry Lab',
        'Slime Making Kit Glow', 'Puzzle Mat Play 6 Tiles', 'Toy Sword Shield Set',
        'Kite Large Rainbow Delta', 'Scooter Foldable Kids', 'Yo Yo Professional Metal',
        'Spinning Top Premium Wooden', 'Magic Tricks Set 50', 'Marbles Set Classic Glass 50',
        'Dollhouse Furniture Wooden', 'Fingerprint Kit Detective', 'Rocket Launcher Foam Air',
        'Balance Bike Toddler', 'Play Tent Castle Indoor', 'Walkie Talkie Kids 3 Channel',
        'Toy Cash Register Playset', 'Bubble Machine Automatic 3000', 'Binoculars Kids Compact',
        'Karaoke Machine Bluetooth', 'Dinosaur Toy Figure Set 12', 'Play Kitchen Set 20 Piece',
        'Tool Bench Workshop Toy', 'Car Track Race Set 10ft', 'Jumping Frog Toy Wind Up',
        'Fidget Spinner Set 5', 'Marble Run 100 Pieces', 'Puppet Show Theater',
        'Trampoline Indoor 36 inch', 'Rocking Horse Plush', 'Train Table Playmat 4x6',
        'Toy Drum Set Music', 'Easel Chalkboard Whiteboard', 'Sewing Kit Kids Craft',
        'Robot Toy Programmable', 'Painting Set Watercolor 24',
    ], (5, 80)),
    'automotive': ([
        'Car Seat Cover Set 4 Pack', 'Dashboard Phone Mount Holder', 'Car Vacuum Cleaner 12V',
        'LED Headlight Bulbs 6000K', 'Tire Inflator Air Compressor', 'Car Floor Mats All Weather',
        'Dash Cam Front And Rear', 'Car Charger USB Fast 3.1A', 'Sun Shade Windshield Foldable',
        'Car Organizer Back Seat Storage', 'Steering Wheel Cover Leather', 'Seat Gap Filler Car',
        'Car Trunk Organizer Foldable', 'Window Visor Rain Guard', 'License Plate Frame Carbon',
        'Car Wax Polish Kit', 'Microfiber Towel 12 Pack', 'Air Freshener Long Lasting',
        'Rear View Mirror Blind Spot', 'Car Battery Charger 12V', 'Jump Starter Power Bank 2000A',
        'Seat Cushion Memory Foam', 'GPS Tracker Magnetic', 'Car Emergency Kit 40 Piece',
        'Roof Rack Crossbars', 'Tire Pressure Gauge Digital', 'Magnetic Phone Car Mount',
        'LED Strip Interior Lights', 'Car Blind Spot Mirror 2 Pack', 'Oil Filter Wrench Tool',
        'Jack Stand 3 Ton Pair', 'Car Cover Waterproof Outdoor', 'Hand Gloves Mechanic Work',
        'Nitrile Gloves Disposable 100pk', 'Funnel Set Oil Change', 'Tire Repair Kit Plug',
        'Ratchet Wrench Set 72 Tooth', 'Socket Set 46 Piece', 'Battery Terminal Cleaner',
        'Headlight Restoration Kit', 'Touch Up Paint Pens 5 Pack', 'Keychain Leather Key Holder',
        'Car Trash Can Mini', 'Drink Holder Expander', 'Window Shade Baby Kids',
        'Parking Sensor Backup Camera', 'Steering Wheel Desk Tray', 'Mud Flaps Splash Guards',
        'Center Console Organizer', 'Seat Belt Pad Comfort',
    ], (5, 150)),
    'books': ([
        'Atomic Habits James Clear', 'Rich Dad Poor Dad Kiyosaki', 'Think And Grow Rich Hill',
        '48 Laws Of Power Greene', 'Deep Work Cal Newport', 'The Alchemist Paulo Coelho',
        'The Power Of Habit Duhigg', 'Zero To One Peter Thiel', 'Start With Why Sinek',
        'The Lean Startup Ries', 'Who Moved My Cheese Johnson', 'The 7 Habits Covey',
        'How To Win Friends Carnegie', 'Influence Psychology Cialdini', 'Good To Great Collins',
        'Outliers Malcolm Gladwell', 'The Subtle Art Not Giving', 'Ikigai Japanese Purpose',
        'Man Search For Meaning Frankl', 'Mindset Carol Dweck', 'The Psychology Of Money Housel',
        'Daring Greatly Brene Brown', 'Grit Angela Duckworth', 'The 5 Love Languages Gary',
        'Untamed Glennon Doyle', 'Educated Tara Westover', 'Becoming Michelle Obama',
        'Sapiens Harari', 'Homo Deus Harari', '21 Lessons 21st Century Harari',
        'The Art Of War Sun Tzu', 'Meditations Marcus Aurelius', 'The Obstacle Way Holiday',
        'Ego Is Enemy Holiday', 'Stillness Is Key Holiday', 'The Daily Stoic Holiday',
        'Four Thousand Weeks Burkeman', 'Breath New Science Nestor', 'Why We Sleep Matthew Walker',
        'The Body Bill Bryson', 'Enlightenment Now Pinker', 'Factfulness Rosling',
        'Thinking Fast Slow Kahneman', 'Noise Kahneman', 'Misbehaving Thaler',
        'Nudge Thaler', 'Predictably Irrational Ariely', 'Drive Daniel Pink',
        'When Caroline Webb', 'The Happiness Project Rubin',
    ], (8, 40)),
    'jewelry': ([
        'Gold Plated Necklace Pendant', 'Pearl Earrings Stud 8mm', 'Silver Bracelet Chain',
        'Diamond Ring Engagement 1ct', 'Bangles Set Gold Polish', 'Anklet Silver Adjustable',
        'Nose Pin 24K Gold', 'Ear Cuff Gold Trendy', 'Pendant Set Kundan Work',
        'Toe Ring Silver Pair', 'Brooch Pin Enamel Flower', 'Cufflinks Silver Men',
        'Locket Heart Shape Gold', 'Earring Hoop Gold Large', 'Ring Adjustable Silver',
        'Mangalsutra Gold Design', 'Necklace Set Pearl Layered', 'Bracelet Charm Silver',
        'Tikka Maang Traditional Gold', 'Waist Chain Gold Belly', 'Ring Stackable Gold 5pc',
        'Earring Drop Gold Design', 'Pendant Oxidized Silver', 'Bangle Bracelet Cuff Gold',
        'Anklet Bell Silver', 'Nath Nose Ring Gold', 'Choker Necklace Velvet Gold',
        'Ring Wedding Band Gold', 'Earring Stud Diamond', 'Pendant Compartment Gold',
        'Bracelet Gold Beaded', 'Mala Necklace Ruby Beads', 'Ring Cocktail Silver Crystal',
        'Jhumka Earrings Traditional', 'Bali Earring Gold', 'Chain Necklace Gold 20 inch',
        'Earring French Hook Crystal', 'Pendant Tree Of Life', 'Bracelet Leather Gold Accent',
        'Ring Signet Men Silver', 'Cuff Bracelet Wide Gold', 'Necklace Bar Gold Minimal',
        'Earring Stud Pearl White', 'Bangle Set Glass Polish', 'Ring Emerald Green Silver',
        'Pendant Cross Gold', 'Charm Bead Gold 14k', 'Earring Tassel Thread',
        'Anklet Gold Light Weight', 'Brooch Vintage Gold Flower',
    ], (10, 500)),
    'baby-products': ([
        'Baby Diaper Premium 72 Pack', 'Baby Wipes Water 720ct', 'Baby Bottle Glass 250ml',
        'Baby Stroller Foldable Light', 'Baby Carrier Breathable Mesh', 'Crib Bedding Set 5pc',
        'Baby Monitor Video Night Vision', 'High Chair Wooden Adjustable', 'Baby Swing Automatic',
        'Diaper Bag Backpack Large', 'Baby Playpen Fence 6 Panel', 'Baby Walker Activity Musical',
        'Changing Pad Waterproof', 'Baby Bouncer Vibrating Seat', 'Breast Pump Electric Double',
        'Baby Food Maker Steamer Blender', 'Baby Bath Tub Foldable', 'Baby Towel Hooded Organic',
        'Baby Nail Trimmer Electric', 'Baby Thermometer Digital Fast', 'Pacifier Set Silicone 4 Pack',
        'Teether Silicone Fruit Shape', 'Baby Blanket Swaddle Muslin', 'Sippy Cup Spill Proof 300ml',
        'Baby Spoon Fork Set Silicone', 'Baby Plate Suction Bowl', 'Baby Knee Pads Crawling',
        'Baby Gate Pressure Mounted', 'Night Light Baby Projector', 'Baby Humidifier Cool Mist',
        'Diaper Pail Odor Lock', 'Baby Laundry Detergent Natural', 'Car Seat Infant Convertible',
        'Baby Head Support Pillow', 'Baby Sunscreen SPF 50', 'Baby Lotion Moisturizing 500ml',
        'Baby Shampoo Tear Free', 'Baby Oil Natural Massage', 'Baby Powder Talc Free',
        'Diaper Cream Zinc Oxide', 'Baby Rash Guard UV Swim', 'Baby Socks Non Slip 6 Pack',
        'Baby Hat Sun Protection', 'Baby Booties Soft Sole', 'Baby Mitten Scratch Preventer',
        'Baby Swimsuit Float Vest', 'Baby Book Black White Contrast', 'Baby Rattle Set Wooden 3pk',
        'Baby Activity Gym Mat', 'Baby Musical Toy Piano',
    ], (5, 120)),
    'pet-supplies': ([
        'Dog Food Dry Premium 15kg', 'Cat Litter Clumping 10kg', 'Dog Bed Orthopedic Large',
        'Cat Tree Tower Scratching', 'Dog Leash Reflective 5ft', 'Cat Toy Feather Wand',
        'Pet Carrier Airline Approved', 'Dog Crate Folding Metal', 'Cat Food Wet 24 Pack',
        'Dog Treats Training 1kg', 'Pet Grooming Brush Deshedding', 'Nail Clipper Pet Professional',
        'Pet Bowl Stainless 2 Pack', 'Cat Litter Box Enclosed', 'Dog Harness No Pull Adjustable',
        'Pet Mat Waterproof Feeding', 'Flea Tick Collar Dog', 'Dog Shampoo Oatmeal 500ml',
        'Cat Scratching Post Sisal', 'Pet Water Fountain Automatic', 'Dog Toy Squeaky Ball 4pk',
        'Cat Nip Organic Dried 50g', 'Dog Chew Bone Durable', 'Pet Bed Cave Self Warming',
        'Dog Collar Leather Personalized', 'Cat Harness Vest Escape Proof', 'Pet ID Tag Custom Engraved',
        'Dog Waste Bags 180 Pack', 'Pet First Aid Kit 30 Piece', 'Cat Window Perch Hammock',
        'Dog Muzzle Basket Breathable', 'Pet Hair Remover Roller', 'Cat Tunnel Collapsible 3 Way',
        'Dog Pool Splash Pad Summer', 'Pet Travel Bowl Collapsible', 'Dog Vest Life Jacket Float',
        'Cat Brush Glove Grooming', 'Pet Stroller Dog Cat', 'Dog Diaper Male Wrap Reusable',
        'Cat Food Mat Silicone', 'Pet Gate Stair Pressure Mount', 'Dog Paw Protector Wax',
        'Cat Dental Treats 60pk', 'Pet Heating Pad Warm', 'Dog Backpack Carrier Hiking',
        'Cat Carrier Backpack Bubble', 'Pet Seat Cover Car', 'Dog Agility Training Kit',
        'Cat Grass Growing Kit', 'Pet Camera Treat Dispenser',
    ], (5, 100)),
    'groceries': ([
        'Organic Honey Pure 500g', 'Extra Virgin Olive Oil 1L', 'Basmati Rice Premium 5kg',
        'Almonds Raw California 1kg', 'Green Tea Matcha Ceremonial', 'Dark Chocolate 70% 200g',
        'Coconut Oil Virgin 500ml', 'Mixed Nuts Roasted 1kg', 'Coffee Beans Arabica 500g',
        'Protein Powder Whey 2kg', 'Chia Seeds Organic 500g', 'Maple Syrup Pure 250ml',
        'Dried Apricots Turkish 500g', 'Oats Rolled Organic 1kg', 'Peanut Butter Crunchy 510g',
        'Cashews Whole Roasted 500g', 'Quinoa White Organic 1kg', 'Trail Mix Energy 500g',
        'Coconut Water Pure 1L', 'Almond Milk Unsweetened 1L', 'Granola Clusters Honey 400g',
        'Dates Medjool Premium 500g', 'Muesli Swiss Style 500g', 'Turmeric Powder Organic 250g',
        'Black Pepper Whole 200g', 'Cinnamon Sticks Ceylon 100g', 'Sea Salt Pink Himalayan 1kg',
        'Apple Cider Vinegar Raw 500ml', 'Sesame Oil Cold Pressed 250ml', 'Ghee Clarified Butter 500g',
        'Brown Rice Organic 2kg', 'Chickpeas Dry 1kg', 'Red Lentils Split 1kg',
        'Flax Seeds Ground 500g', 'Sunflower Seeds Kernel 500g', 'Pumpkin Seeds Raw 500g',
        'Coconut Chips Toasted 200g', 'Dried Mango Slices 250g', 'Walnuts English Shelled 500g',
        'Pistachios Roasted Salted 500g', 'Hazelnuts Raw 500g', 'Brazil Nuts Raw 500g',
        'Macadamia Nuts Roasted 250g', 'Pine Nuts Raw 200g', 'Cacao Powder Raw Organic 250g',
        'Goji Berries Dried 500g', 'Spirulina Powder Organic 250g', 'Matcha Green Tea 100g',
        'Protein Bars 12 Pack', 'Coconut Palm Sugar 500g',
    ], (3, 50)),
    'office-supplies': ([
        'Standing Desk Adjustable Height', 'Office Chair Ergonomic Mesh', 'Desk Lamp LED Eye Care',
        'Monitor Stand Riser Bamboo', 'Keyboard Wired USB Full Size', 'Mouse Wireless Silent Click',
        'Notebook A5 Hardcover 200pg', 'Pen Set Ballpoint 12 Pack', 'Stapler Heavy Duty 50 Sheet',
        'Paper Shredder Cross Cut 12L', 'Whiteboard Magnetic 36x24', 'Bulletin Board Cork 24x36',
        'Desk Organizer Acrylic 5 Compartment', 'File Folder Hanging 25 Pack', 'Binder Ring 3 Inch 4 Pack',
        'Calculator Desktop Solar Dual', 'Tape Dispenser Desk Premium', 'Scissors Stainless 8 inch',
        'Post It Notes 12 Pack', 'Paper Clips Color 100 Pack', 'Push Pins Map 200 Pack',
        'Highlighter Set 6 Color', 'Pencil Mechanical 0.7mm 5pk', 'Eraser Whiteboard Magnetic',
        'Correction Tape 6 Pack', 'Letter Tray Stackable 3 Tier', 'Document Camera USB 1080p',
        'Business Card Holder Desk', 'Pencil Case Canvas Large', 'Ruler Stainless Steel 12 inch',
        'Compass Geometry Set', 'Glue Stick 24 Pack', 'Marker Permanent Fine Point 10pk',
        'Label Maker Thermal Printer', 'Mouse Pad Extended XXL', 'Wrist Rest Gel Memory Foam',
        'Cable Management Sleeve 6ft', 'Surge Protector 6 Outlet', 'Desk Bike Under Desk',
        'Foot Rest Under Desk Adjustable', 'Task Light Clip On', 'Bookend Metal Adjustable Pair',
        'Paper Tray Desktop Vertical', 'Stamp Self Inking Custom', 'Envelope Window 100 Pack',
        'Clipboard Letter Size Hardboard', 'Dry Erase Markers 8 Color', 'Sticky Note Desk Pad Cube',
        'Desk Drawer Organizer Tray', 'Document Holder Desktop',
    ], (3, 200)),
    'music': ([
        'Guitar Acoustic Steel String', 'Headphones Over Ear Studio', 'Bluetooth Speaker Portable 30W',
        'Digital Piano Keyboard 88 Key', 'Ukulele Soprano Mahogany', 'Microphone Dynamic Cardioid',
        'Violin 4/4 Full Size', 'Drum Sticks Hickory 5A Pair', 'Electric Guitar Starter Kit',
        'Audio Interface USB 2 Channel', 'Studio Monitor Speaker Pair', 'MIDI Controller Keyboard 49 Key',
        'Acoustic Guitar Strings 12pk', 'Capo Guitar Clamp', 'Guitar Pick Variety 24 Pack',
        'Music Stand Sheet Foldable', 'Earphones In Ear Monitor', 'DJ Controller 2 Channel',
        'Harmonica Key C Professional', 'Recorder Soprano Baroque', 'Saxophone Alto Brass Gold',
        'Trumpet Bb Standard', 'Flute Closed Hole C', 'Clarinet Bb Wooden',
        'Djembe Drum 12 inch', 'Keyboard Stool Adjustable', 'Guitar Amp Modeling 15W',
        'Bass Guitar 4 String', 'Mandolin Acoustic A Style', 'Cajon Box Drum Percussion',
        'Tambourine Hand 10 inch', 'Triangle Musical Steel 6 inch', 'Bongo Drums Wood 7/8 inch',
        'Kazoo Metal Professional', 'Xylophone Glockenspiel 27 Note', 'Piano Bench Padded Adjustable',
        'Sheet Music Book Classical', 'Guitar Wall Mount Holder', 'Pickup Acoustic Sound Hole',
        'Loop Station Pedal', 'Effect Pedal Distortion', 'Tuner Clip On Chromatic',
        'Metronome Mechanical Wind Up', 'Earplugs Musician HiFi', 'Practice Pad Snare 12 inch',
        'Guitar Strap Leather Padded', 'Cable Instrument 1/4 10ft', 'Guitar Case Hard Shell',
        'Drum Key Lug Tension', 'Guitar Stand Foldable A Frame',
    ], (10, 300)),
    'garden-outdoor': ([
        'Plant Pot Ceramic 10 inch', 'Gardening Tool Set 7 Piece', 'Hose Pipe Expandable 50ft',
        'Flower Seeds Mix 20 Varieties', 'Raised Garden Bed Wood 4x4', 'Compost Bin Tumbler 60L',
        'Watering Can Galvanized 2L', 'Pruning Shears Bypass Sharp', 'Garden Gloves Latex Coated',
        'Outdoor String Lights 50ft', 'Patio Furniture Set 4 Piece', 'BBQ Grill Charcoal 22 inch',
        'Hammock Double Cotton', 'Fire Pit Table Propane', 'Garden Bench Wooden Rustic',
        'Bird Feeder Hang Tube', 'Solar Lights Pathway 8 Pack', 'Knee Pad Gardening Foam',
        'Plant Stand Bamboo 3 Tier', 'Trowel Hand Stainless Steel', 'Wheelbarrow Garden Steel 6cuft',
        'Spade Shovel Round Point', 'Rake Leaf Adjustable', 'Weed Puller Standing Tool',
        'Axe Splitting Wood 3.5lb', 'Lopper Branch Cutting 28 inch', 'Lawn Mower Manual Reel',
        'Edger Lawn Manual Wheel', 'Sprinkler Oscillating Lawn', 'Fertilizer Organic All Purpose 5kg',
        'Potting Mix Soil 25L', 'Mulch Bark 50L', 'Pebbles Decorative White 10kg',
        'Garden Statue Resin Owl', 'Wind Chime Metal 36 inch', 'Outdoor Rug Patio 5x7',
        'Umbrella Patio Offset 10ft', 'Cushion Set Outdoor 4 Pack', 'Mosquito Repeller Outdoor',
        'Pergola Kit Wood 10x10', 'Fence Panel Privacy 6ft', 'Compost Starter Bacteria',
        'Plant Food Liquid 1L', 'Seed Tray Starter 72 Cell', 'Greenhouse Polycarbonate 6x4',
        'Rain Barrel Water 50 Gal', 'Garden Netting Bird Protection', 'Trellis Climbing Plant 6ft',
        'Edging Lawn Flexible 20ft', 'Glow In Dark Stones 500g',
    ], (5, 200)),
    'shoes': ([
        'Running Shoes Men Breathable', 'Sneakers Women White Casual', 'Hiking Boots Waterproof Men',
        'Formal Shoes Men Oxford', 'Sandals Women Flat Summer', 'Slippers Men Memory Foam',
        'Basketball Shoes High Top', 'Training Shoes Crossfit Men', 'Loafers Women Slip On',
        'Boots Ankle Leather Women', 'Sports Shoes Kids Running', 'Canvas Shoes Unisex Low Top',
        'Wedges Heels Women Platform', 'Heels Pump Women Stiletto', 'Espadrilles Women Canvas',
        'Moccasins Men Driving', 'Chelsea Boots Men Elastic', 'Flip Flops Beach Rubber',
        'Sneakers Slip On Mesh', 'Walking Shoes Men Lightweight', 'Trail Running Shoes Grip',
        'Tennis Shoes Court Men', 'Golf Shoes Spiked Men', 'Football Cleats Firm Ground',
        'Cycling Shoes Road Clip', 'Skate Shoes Suede Low', 'Work Boots Steel Toe',
        'Rain Boots Women Tall', 'Snow Boots Insulated Men', 'Dance Shoes Latin Women',
        'Ballet Flats Women Cute', 'Platform Sneakers Chunky', 'Gladiator Sandals Flat',
        'Slide Sandals Men Sport', 'Clogs Garden Waterproof', 'Slippers House Cozy Fuzzy',
        'Sneakers High Top Fashion', 'Casual Shoes Men Lace Up', 'Oxford Shoes Women Vintage',
        'Boots Combat Chunky Lace', 'Espadrilles Wedge Summer', 'Mules Women Open Back',
        'Loafers Men Tassel', 'Driving Shoes Men Leather', 'Hiking Sandals Men Sport',
        'Water Shoes Swim Quick Dry', 'Yoga Socks Non Slip Grip', 'Sneakers Platform Women Thick',
        'Creeper Shoes Platform', 'Joggers Slip On Breathable',
    ], (15, 150)),
    'watches': ([
        'Smart Watch Fitness Tracker Pro', 'Analog Watch Men Stainless', 'Digital Watch Men Sports',
        'Chronograph Watch Leather Strap', 'Watch Women Crystal Diamond', 'Diver Watch 200m Waterproof',
        'Minimalist Watch Slim Design', 'Automatic Watch Skeleton Back', 'Gold Watch Women Luxury',
        'Military Watch Tactical Men', 'Fashion Watch Women Mesh Band', 'Sport Watch Stopwatch Alarm',
        'Dress Watch Thin Casual', 'Luxury Watch Rose Gold', 'Watch Men Silver Sunray Dial',
        'Women Watch Ceramic White', 'Unisex Watch Minimal Round', 'Pilot Watch Aviation Style',
        'Racing Watch Tachymeter Bezel', 'Field Watch Canvas Strap', 'Smart Watch Women Heart Rate',
        'GPS Watch Running Tracker', 'Altitude Watch Barometer', 'Moon Phase Watch Dress',
        'World Time Watch GMT', 'Skeleton Watch Open Heart', 'Titanium Watch Lightweight',
        'Carbon Fiber Watch Sport', 'Wood Watch Natural Bamboo', 'Couple Watch Set His Hers',
        'Diamond Watch Women 1ct', 'Sapphire Crystal Watch Scratch', 'Leather Band Watch Vintage',
        'Nato Strap Watch Military', 'Bracelet Watch Women Gold', 'Digital Compass Watch Outdoor',
        'Heart Rate Monitor Watch', 'Swim Watch Waterproof 100m', 'Dual Time Zone Watch Travel',
        'Perpetual Calendar Watch', 'Rectangular Watch Art Deco', 'Round Watch Classic Gold',
        'Ribbon Watch Women Satin', 'Chain Link Watch Women', 'Rubber Strap Watch Dive',
        'Mesh Band Watch Silver', 'Pocket Watch Antique Brass', 'Smart Band Fitness Slim',
        'Kids Watch Cartoon Digital', 'Watch Winder Box 2 Slot',
    ], (15, 500)),
    'bags-luggage': ([
        'Backpack Laptop 15.6 inch', 'Suitcase Carry On 20 inch', 'Duffel Bag Sports Large',
        'Handbag Women Tote Leather', 'Messenger Bag Canvas Shoulder', 'Travel Bag Weekend 30L',
        'Laptop Bag Briefcase Leather', 'Crossbody Bag Women Small', 'Waist Pack Fanny Belt',
        'Sling Bag Chest Casual', 'School Backpack Kids Printed', 'Hiking Backpack 60L Waterproof',
        'Gym Bag Duffle Water Resistant', 'Luggage Set Hardshell 3 Piece', 'Travel Organizer Packing Cubes 6pk',
        'Cosmetic Bag Travel Toiletry', 'Shoulder Bag Women Chain', 'Clutch Evening Bag Rhinestone',
        'Beach Bag Tote Straw', 'Diaper Bag Backpack Mom', 'Briefcase Leather Executive',
        'Laptop Sleeve Neoprene 13 inch', 'Camera Bag DSLR Insert', 'Wine Bag Tote 2 Bottles',
        'Shopping Bag Foldable Reusable', 'Lunch Bag Insulated Cooler', 'Tool Bag Canvas Heavy Duty',
        'Garment Bag Suit Travel Foldable', 'Jewelry Roll Travel Organizer', 'Passport Holder RFID Blocking',
        'Travel Wallet Document Organizer', 'Shoe Bag Travel 2 Pair', 'Laundry Bag Mesh Travel',
        'Dry Bag Waterproof 20L', 'Backpack Anti Theft Lock', 'Tote Bag Work Large Capacity',
        'Bucket Bag Women Drawstring', 'Satchel Bag Women Vintage', 'Hobo Bag Women Leather Soft',
        'Belt Bag Trendy Crossbody', 'Mini Backpack Fashion Women', 'Rucksack Canvas Casual',
        'Bicycle Bag Pannier Waterproof', 'Laptop Messenger 14 inch', 'Tech Organizer Cable Pouch',
        'Makeup Train Case Rolling', 'First Aid Bag Emergency', 'Cooler Bag Soft Sided 30 Can',
        'Trunk Luggage Hard Shell 28in', 'Wheeled Duffel Rolling',
    ], (10, 200)),
    'computer-accessories': ([
        'Wireless Mouse Bluetooth 5.0', 'Mechanical Keyboard RGB Red Switch', 'USB Hub 7 Port Aluminum',
        'Monitor 27 inch 4K IPS', 'External Hard Drive 2TB USB 3.0', 'Laptop Stand Aluminum Adjustable',
        'Webcam 4K Streaming Pro', 'Gaming Mouse Pad XL RGB', 'USB C Cable Fast Charging 6ft',
        'Desk Lamp LED Clamp', 'Surge Protector Tower 12 Outlet', 'Mouse Wrist Rest Gel',
        'Keyboard Wrist Rest Memory Foam', 'Monitor Light Bar Screen', 'Laptop Sleeve 15.6 inch',
        'Cable Management Box Wood', 'USB WiFi Adapter AC1200', 'Micro SD Card 256GB',
        'Thumb Drive 64GB USB 3.0', 'HDMI Cable 2.1 8K 6ft', 'DisplayPort Cable 4K 10ft',
        'USB Extension Cable 10ft', 'Laptop Charger 65W Type C', 'Graphics Card RTX 4060',
        'Internal SSD 1TB NVMe', 'Desktop RAM 32GB DDR5', 'CPU Cooler Air Tower',
        'Power Supply 750W Modular', 'Motherboard B760 WiFi', 'Computer Case Mid Tower RGB',
        'Case Fan 120mm RGB 3 Pack', 'Thermal Paste CPU 4g', 'Sata Cable 3 Pack',
        'Screwdriver Kit Electronics 60', 'Anti Static Wrist Strap', 'Compressed Air Duster 10oz',
        'Screen Cleaning Kit Phone', 'Laptop Lock Cable Security', 'Privacy Screen Filter 15.6in',
        'VESA Monitor Mount Arm Dual', 'TV Wall Mount Full Motion', 'Ethernet Cable Cat8 50ft',
        'Modem Router Combo WiFi 6', 'Network Switch 5 Port Gigabit', 'Powerline Adapter 1200Mbps',
        'UPS Backup Battery 600VA', 'Surge Protector Wall Tap 3 Outlet', 'Desk Cable Tray Wire Management',
        'Monitor Stand Riser 2 Tier', 'Keyboard Cleaning Gel',
    ], (5, 300)),
}

def seed_products():
    db = SessionLocal()
    categories = {c.slug: c for c in db.query(Category).all()}
    total = 0
    for slug, (titles, price_range) in PRODUCTS.items():
        cat = categories.get(slug)
        if not cat:
            print(f'  SKIP: category "{slug}" not found')
            continue
        existing = db.query(Product).filter_by(category_id=cat.id).count()
        if existing >= 50:
            print(f'  {cat.name}: already {existing} products')
            continue
        price_min, price_max = price_range
        added = 0
        for i, title in enumerate(titles):
            slugified = slugify(title) + '-' + str(random.randint(10000, 99999))
            platform = PLATFORMS[i % len(PLATFORMS)]
            price = round(random.uniform(price_min, price_max), 2)
            old_price = round(price * random.uniform(1.15, 1.6), 2) if random.random() < 0.5 else None
            rating = round(random.uniform(3.5, 5.0), 1)
            is_featured = random.random() < 0.25
            is_new = random.random() < 0.30
            currency = random.choice(CURRENCIES)
            image = f'https://picsum.photos/seed/{slug}{i}/400/400'
            affiliate_url = {
                'amazon': f'https://amazon.com/dp/B{random.randint(1000000000,9999999999)}?tag=shafi-20',
                'daraz': f'https://daraz.pk/products/{slugified}/p/{random.randint(100000000,999999999)}',
                'alibaba': f'https://alibaba.com/product-detail/{slugified}_{random.randint(100000000,999999999)}.html',
                'aliexpress': f'https://aliexpress.com/item/{random.randint(1000000000,9999999999)}.html',
            }[platform]
            db.add(Product(
                title=title, slug=slugified,
                short_description=f'Premium {title.lower()} - quality guaranteed',
                description=f'Shop the best {title.lower()} online. High quality, great price, fast shipping. Order now!',
                image=image, price=price, old_price=old_price, rating=rating,
                category_id=cat.id, currency=currency, is_active=True,
                affiliate_platform=platform, affiliate_url=affiliate_url,
                is_featured=is_featured, is_new=is_new,
            ))
            added += 1
            total += 1
        print(f'  {cat.name}: added {added} products')
    db.commit()
    db.close()
    print(f'\nDone! {total} products added total.')

if __name__ == '__main__':
    seed_products()
